2021-04-24 21:41:48,132 WARNING root 0
2021-04-24 21:41:48,138 WARNING root 0
2021-04-24 21:41:48,155 WARNING root 0
2021-04-24 21:41:49,042 WARNING root 0
2021-04-24 21:41:50,046 WARNING root 0
2021-04-24 21:42:01,075 INFO django.utils.autoreload E:\Python\Yandex\Projects\SocialNetworkOnPythonDjango\SocialNetwork\socketio_app\views.py changed, reloading.
2021-04-24 21:42:01,075 DEBUG asyncio Using proactor: IocpProactor
2021-04-24 21:42:02,042 WARNING root 0
2021-04-24 21:42:02,077 WARNING root 0
2021-04-24 21:42:02,077 WARNING root 0
2021-04-24 21:42:02,124 WARNING root 0
2021-04-24 21:42:02,755 WARNING root 0
2021-04-24 21:42:14,632 INFO django.utils.autoreload E:\Python\Yandex\Projects\SocialNetworkOnPythonDjango\SocialNetwork\socketio_app\views.py changed, reloading.
2021-04-24 21:42:14,632 DEBUG asyncio Using proactor: IocpProactor
2021-04-24 21:42:15,758 ERROR engineio.server message handler error
Traceback (most recent call last):
  File "E:\Python\venvs\SocialNetworkOnPythonDjango\lib\site-packages\engineio\server.py", line 596, in _trigger_event
    return self.handlers[event](*args)
  File "E:\Python\venvs\SocialNetworkOnPythonDjango\lib\site-packages\socketio\server.py", line 740, in _handle_eio_message
    self._handle_connect(eio_sid, pkt.namespace, pkt.data)
  File "E:\Python\venvs\SocialNetworkOnPythonDjango\lib\site-packages\socketio\server.py", line 636, in _handle_connect
    success = self._trigger_event(
  File "E:\Python\venvs\SocialNetworkOnPythonDjango\lib\site-packages\socketio\server.py", line 712, in _trigger_event
    return self.handlers[namespace][event](*args)
  File "E:\Python\Yandex\Projects\SocialNetworkOnPythonDjango\SocialNetwork\socketio_app\views.py", line 272, in connect
    print([environ[0]['headers']])
KeyError: 0
2021-04-24 21:42:15,779 ERROR engineio.server message handler error
Traceback (most recent call last):
  File "E:\Python\venvs\SocialNetworkOnPythonDjango\lib\site-packages\engineio\server.py", line 596, in _trigger_event
    return self.handlers[event](*args)
  File "E:\Python\venvs\SocialNetworkOnPythonDjango\lib\site-packages\socketio\server.py", line 740, in _handle_eio_message
    self._handle_connect(eio_sid, pkt.namespace, pkt.data)
  File "E:\Python\venvs\SocialNetworkOnPythonDjango\lib\site-packages\socketio\server.py", line 636, in _handle_connect
    success = self._trigger_event(
  File "E:\Python\venvs\SocialNetworkOnPythonDjango\lib\site-packages\socketio\server.py", line 712, in _trigger_event
    return self.handlers[namespace][event](*args)
  File "E:\Python\Yandex\Projects\SocialNetworkOnPythonDjango\SocialNetwork\socketio_app\views.py", line 272, in connect
    print([environ[0]['headers']])
KeyError: 0
2021-04-24 21:42:16,058 ERROR engineio.server message handler error
Traceback (most recent call last):
  File "E:\Python\venvs\SocialNetworkOnPythonDjango\lib\site-packages\engineio\server.py", line 596, in _trigger_event
    return self.handlers[event](*args)
  File "E:\Python\venvs\SocialNetworkOnPythonDjango\lib\site-packages\socketio\server.py", line 740, in _handle_eio_message
    self._handle_connect(eio_sid, pkt.namespace, pkt.data)
  File "E:\Python\venvs\SocialNetworkOnPythonDjango\lib\site-packages\socketio\server.py", line 636, in _handle_connect
    success = self._trigger_event(
  File "E:\Python\venvs\SocialNetworkOnPythonDjango\lib\site-packages\socketio\server.py", line 712, in _trigger_event
    return self.handlers[namespace][event](*args)
  File "E:\Python\Yandex\Projects\SocialNetworkOnPythonDjango\SocialNetwork\socketio_app\views.py", line 272, in connect
    print([environ[0]['headers']])
KeyError: 0
2021-04-24 21:42:16,072 ERROR engineio.server message handler error
Traceback (most recent call last):
  File "E:\Python\venvs\SocialNetworkOnPythonDjango\lib\site-packages\engineio\server.py", line 596, in _trigger_event
    return self.handlers[event](*args)
  File "E:\Python\venvs\SocialNetworkOnPythonDjango\lib\site-packages\socketio\server.py", line 740, in _handle_eio_message
    self._handle_connect(eio_sid, pkt.namespace, pkt.data)
  File "E:\Python\venvs\SocialNetworkOnPythonDjango\lib\site-packages\socketio\server.py", line 636, in _handle_connect
    success = self._trigger_event(
  File "E:\Python\venvs\SocialNetworkOnPythonDjango\lib\site-packages\socketio\server.py", line 712, in _trigger_event
    return self.handlers[namespace][event](*args)
  File "E:\Python\Yandex\Projects\SocialNetworkOnPythonDjango\SocialNetwork\socketio_app\views.py", line 272, in connect
    print([environ[0]['headers']])
KeyError: 0
2021-04-24 21:42:16,094 ERROR engineio.server message handler error
Traceback (most recent call last):
  File "E:\Python\venvs\SocialNetworkOnPythonDjango\lib\site-packages\engineio\server.py", line 596, in _trigger_event
    return self.handlers[event](*args)
  File "E:\Python\venvs\SocialNetworkOnPythonDjango\lib\site-packages\socketio\server.py", line 740, in _handle_eio_message
    self._handle_connect(eio_sid, pkt.namespace, pkt.data)
  File "E:\Python\venvs\SocialNetworkOnPythonDjango\lib\site-packages\socketio\server.py", line 636, in _handle_connect
    success = self._trigger_event(
  File "E:\Python\venvs\SocialNetworkOnPythonDjango\lib\site-packages\socketio\server.py", line 712, in _trigger_event
    return self.handlers[namespace][event](*args)
  File "E:\Python\Yandex\Projects\SocialNetworkOnPythonDjango\SocialNetwork\socketio_app\views.py", line 272, in connect
    print([environ[0]['headers']])
KeyError: 0
2021-04-24 21:42:21,390 INFO django.utils.autoreload E:\Python\Yandex\Projects\SocialNetworkOnPythonDjango\SocialNetwork\socketio_app\views.py changed, reloading.
2021-04-24 21:42:21,391 DEBUG asyncio Using proactor: IocpProactor
2021-04-24 21:42:22,352 ERROR engineio.server message handler error
Traceback (most recent call last):
  File "E:\Python\venvs\SocialNetworkOnPythonDjango\lib\site-packages\engineio\server.py", line 596, in _trigger_event
    return self.handlers[event](*args)
  File "E:\Python\venvs\SocialNetworkOnPythonDjango\lib\site-packages\socketio\server.py", line 740, in _handle_eio_message
    self._handle_connect(eio_sid, pkt.namespace, pkt.data)
  File "E:\Python\venvs\SocialNetworkOnPythonDjango\lib\site-packages\socketio\server.py", line 636, in _handle_connect
    success = self._trigger_event(
  File "E:\Python\venvs\SocialNetworkOnPythonDjango\lib\site-packages\socketio\server.py", line 712, in _trigger_event
    return self.handlers[namespace][event](*args)
  File "E:\Python\Yandex\Projects\SocialNetworkOnPythonDjango\SocialNetwork\socketio_app\views.py", line 272, in connect
    print([environ['headers']])
KeyError: 'headers'
2021-04-24 21:42:22,942 ERROR engineio.server message handler error
Traceback (most recent call last):
  File "E:\Python\venvs\SocialNetworkOnPythonDjango\lib\site-packages\engineio\server.py", line 596, in _trigger_event
    return self.handlers[event](*args)
  File "E:\Python\venvs\SocialNetworkOnPythonDjango\lib\site-packages\socketio\server.py", line 740, in _handle_eio_message
    self._handle_connect(eio_sid, pkt.namespace, pkt.data)
  File "E:\Python\venvs\SocialNetworkOnPythonDjango\lib\site-packages\socketio\server.py", line 636, in _handle_connect
    success = self._trigger_event(
  File "E:\Python\venvs\SocialNetworkOnPythonDjango\lib\site-packages\socketio\server.py", line 712, in _trigger_event
    return self.handlers[namespace][event](*args)
  File "E:\Python\Yandex\Projects\SocialNetworkOnPythonDjango\SocialNetwork\socketio_app\views.py", line 272, in connect
    print([environ['headers']])
KeyError: 'headers'
2021-04-24 21:42:22,974 ERROR engineio.server message handler error
Traceback (most recent call last):
  File "E:\Python\venvs\SocialNetworkOnPythonDjango\lib\site-packages\engineio\server.py", line 596, in _trigger_event
    return self.handlers[event](*args)
  File "E:\Python\venvs\SocialNetworkOnPythonDjango\lib\site-packages\socketio\server.py", line 740, in _handle_eio_message
    self._handle_connect(eio_sid, pkt.namespace, pkt.data)
  File "E:\Python\venvs\SocialNetworkOnPythonDjango\lib\site-packages\socketio\server.py", line 636, in _handle_connect
    success = self._trigger_event(
  File "E:\Python\venvs\SocialNetworkOnPythonDjango\lib\site-packages\socketio\server.py", line 712, in _trigger_event
    return self.handlers[namespace][event](*args)
  File "E:\Python\Yandex\Projects\SocialNetworkOnPythonDjango\SocialNetwork\socketio_app\views.py", line 272, in connect
    print([environ['headers']])
KeyError: 'headers'
2021-04-24 21:42:23,078 ERROR engineio.server message handler error
Traceback (most recent call last):
  File "E:\Python\venvs\SocialNetworkOnPythonDjango\lib\site-packages\engineio\server.py", line 596, in _trigger_event
    return self.handlers[event](*args)
  File "E:\Python\venvs\SocialNetworkOnPythonDjango\lib\site-packages\socketio\server.py", line 740, in _handle_eio_message
    self._handle_connect(eio_sid, pkt.namespace, pkt.data)
  File "E:\Python\venvs\SocialNetworkOnPythonDjango\lib\site-packages\socketio\server.py", line 636, in _handle_connect
    success = self._trigger_event(
  File "E:\Python\venvs\SocialNetworkOnPythonDjango\lib\site-packages\socketio\server.py", line 712, in _trigger_event
    return self.handlers[namespace][event](*args)
  File "E:\Python\Yandex\Projects\SocialNetworkOnPythonDjango\SocialNetwork\socketio_app\views.py", line 272, in connect
    print([environ['headers']])
KeyError: 'headers'
2021-04-24 21:42:23,084 ERROR engineio.server message handler error
Traceback (most recent call last):
  File "E:\Python\venvs\SocialNetworkOnPythonDjango\lib\site-packages\engineio\server.py", line 596, in _trigger_event
    return self.handlers[event](*args)
  File "E:\Python\venvs\SocialNetworkOnPythonDjango\lib\site-packages\socketio\server.py", line 740, in _handle_eio_message
    self._handle_connect(eio_sid, pkt.namespace, pkt.data)
  File "E:\Python\venvs\SocialNetworkOnPythonDjango\lib\site-packages\socketio\server.py", line 636, in _handle_connect
    success = self._trigger_event(
  File "E:\Python\venvs\SocialNetworkOnPythonDjango\lib\site-packages\socketio\server.py", line 712, in _trigger_event
    return self.handlers[namespace][event](*args)
  File "E:\Python\Yandex\Projects\SocialNetworkOnPythonDjango\SocialNetwork\socketio_app\views.py", line 272, in connect
    print([environ['headers']])
KeyError: 'headers'
2021-04-24 21:43:01,147 INFO django.utils.autoreload E:\Python\Yandex\Projects\SocialNetworkOnPythonDjango\SocialNetwork\socketio_app\views.py changed, reloading.
2021-04-24 21:43:01,148 DEBUG asyncio Using proactor: IocpProactor
2021-04-24 21:43:39,030 INFO django.utils.autoreload E:\Python\Yandex\Projects\SocialNetworkOnPythonDjango\SocialNetwork\socketio_app\views.py changed, reloading.
2021-04-24 21:43:39,031 DEBUG asyncio Using proactor: IocpProactor
2021-04-24 21:44:17,997 INFO django.utils.autoreload E:\Python\Yandex\Projects\SocialNetworkOnPythonDjango\SocialNetwork\socketio_app\views.py changed, reloading.
2021-04-24 21:44:17,999 DEBUG asyncio Using proactor: IocpProactor
2021-04-24 21:44:25,877 INFO django.utils.autoreload E:\Python\Yandex\Projects\SocialNetworkOnPythonDjango\SocialNetwork\socketio_app\views.py changed, reloading.
2021-04-24 21:44:25,879 DEBUG asyncio Using proactor: IocpProactor
2021-04-24 21:46:22,231 INFO django.utils.autoreload E:\Python\Yandex\Projects\SocialNetworkOnPythonDjango\SocialNetwork\socketio_app\views.py changed, reloading.
2021-04-24 21:46:22,232 DEBUG asyncio Using proactor: IocpProactor
2021-04-24 21:48:15,280 INFO django.utils.autoreload E:\Python\Yandex\Projects\SocialNetworkOnPythonDjango\SocialNetwork\socketio_app\views.py changed, reloading.
2021-04-24 21:48:15,281 DEBUG asyncio Using proactor: IocpProactor
2021-04-24 21:48:35,104 INFO django.utils.autoreload E:\Python\Yandex\Projects\SocialNetworkOnPythonDjango\SocialNetwork\socketio_app\views.py changed, reloading.
2021-04-24 21:48:35,105 DEBUG asyncio Using proactor: IocpProactor
2021-04-24 21:49:58,227 INFO django.utils.autoreload E:\Python\Yandex\Projects\SocialNetworkOnPythonDjango\SocialNetwork\socketio_app\views.py changed, reloading.
2021-04-24 21:49:58,229 DEBUG asyncio Using proactor: IocpProactor
2021-04-24 21:50:20,562 INFO django.utils.autoreload E:\Python\Yandex\Projects\SocialNetworkOnPythonDjango\SocialNetwork\socketio_app\views.py changed, reloading.
2021-04-24 21:50:20,563 DEBUG asyncio Using proactor: IocpProactor
2021-04-24 21:50:32,915 INFO django.utils.autoreload E:\Python\Yandex\Projects\SocialNetworkOnPythonDjango\SocialNetwork\socketio_app\views.py changed, reloading.
2021-04-24 21:50:32,917 DEBUG asyncio Using proactor: IocpProactor
2021-04-24 21:50:41,998 INFO django.utils.autoreload E:\Python\Yandex\Projects\SocialNetworkOnPythonDjango\SocialNetwork\socketio_app\views.py changed, reloading.
2021-04-24 21:50:41,998 DEBUG asyncio Using proactor: IocpProactor
2021-04-24 21:51:10,787 INFO django.utils.autoreload E:\Python\Yandex\Projects\SocialNetworkOnPythonDjango\SocialNetwork\socketio_app\views.py changed, reloading.
2021-04-24 21:51:10,788 DEBUG asyncio Using proactor: IocpProactor
2021-04-24 21:53:42,381 INFO django.utils.autoreload E:\Python\Yandex\Projects\SocialNetworkOnPythonDjango\SocialNetwork\socketio_app\views.py changed, reloading.
2021-04-24 21:53:42,382 DEBUG asyncio Using proactor: IocpProactor
2021-04-24 21:55:56,837 INFO django.utils.autoreload E:\Python\Yandex\Projects\SocialNetworkOnPythonDjango\SocialNetwork\socketio_app\views.py changed, reloading.
2021-04-24 21:55:56,837 DEBUG asyncio Using proactor: IocpProactor
2021-04-24 21:58:01,782 INFO django.utils.autoreload E:\Python\Yandex\Projects\SocialNetworkOnPythonDjango\SocialNetwork\socketio_app\views.py changed, reloading.
2021-04-24 21:58:01,782 DEBUG asyncio Using proactor: IocpProactor
2021-04-24 21:59:13,859 INFO django.utils.autoreload E:\Python\Yandex\Projects\SocialNetworkOnPythonDjango\SocialNetwork\socketio_app\views.py changed, reloading.
2021-04-24 21:59:13,860 DEBUG asyncio Using proactor: IocpProactor
2021-04-24 22:00:52,431 INFO django.utils.autoreload E:\Python\Yandex\Projects\SocialNetworkOnPythonDjango\SocialNetwork\socketio_app\views.py changed, reloading.
2021-04-24 22:00:52,431 DEBUG asyncio Using proactor: IocpProactor
2021-04-24 22:01:44,553 INFO django.utils.autoreload E:\Python\Yandex\Projects\SocialNetworkOnPythonDjango\SocialNetwork\socketio_app\views.py changed, reloading.
2021-04-24 22:01:44,554 DEBUG asyncio Using proactor: IocpProactor
2021-04-24 22:02:42,494 INFO django.utils.autoreload E:\Python\Yandex\Projects\SocialNetworkOnPythonDjango\SocialNetwork\socketio_app\views.py changed, reloading.
2021-04-24 22:02:42,495 DEBUG asyncio Using proactor: IocpProactor
2021-04-24 22:06:00,300 INFO django.utils.autoreload E:\Python\Yandex\Projects\SocialNetworkOnPythonDjango\SocialNetwork\socketio_app\views.py changed, reloading.
2021-04-24 22:06:00,301 DEBUG asyncio Using proactor: IocpProactor
2021-04-24 22:06:38,458 DEBUG asyncio Using proactor: IocpProactor
2021-04-24 22:06:47,979 INFO django.utils.autoreload E:\Python\Yandex\Projects\SocialNetworkOnPythonDjango\SocialNetwork\socketio_app\views.py changed, reloading.
2021-04-24 22:06:47,979 DEBUG asyncio Using proactor: IocpProactor
2021-04-24 22:07:13,690 WARNING django.request Not Found: /
2021-04-24 22:07:25,577 INFO django.utils.autoreload E:\Python\Yandex\Projects\SocialNetworkOnPythonDjango\SocialNetwork\socketio_app\views.py changed, reloading.
2021-04-24 22:07:25,578 DEBUG asyncio Using proactor: IocpProactor
2021-04-24 22:08:28,959 INFO django.utils.autoreload E:\Python\Yandex\Projects\SocialNetworkOnPythonDjango\SocialNetwork\socketio_app\views.py changed, reloading.
2021-04-24 22:08:28,959 DEBUG asyncio Using proactor: IocpProactor
2021-04-24 22:09:55,462 INFO django.utils.autoreload E:\Python\Yandex\Projects\SocialNetworkOnPythonDjango\SocialNetwork\socketio_app\views.py changed, reloading.
2021-04-24 22:09:55,462 DEBUG asyncio Using proactor: IocpProactor
2021-04-24 22:10:24,565 DEBUG asyncio Using proactor: IocpProactor
2021-04-24 22:12:05,264 INFO django.utils.autoreload E:\Python\Yandex\Projects\SocialNetworkOnPythonDjango\SocialNetwork\socketio_app\views.py changed, reloading.
2021-04-24 22:12:05,265 DEBUG asyncio Using proactor: IocpProactor
2021-04-24 22:12:15,350 INFO django.utils.autoreload E:\Python\Yandex\Projects\SocialNetworkOnPythonDjango\SocialNetwork\socketio_app\views.py changed, reloading.
2021-04-24 22:12:15,350 DEBUG asyncio Using proactor: IocpProactor
2021-04-24 22:12:25,891 DEBUG asyncio Using proactor: IocpProactor
2021-04-24 22:14:30,485 INFO django.utils.autoreload E:\Python\Yandex\Projects\SocialNetworkOnPythonDjango\SocialNetwork\socketio_app\views.py changed, reloading.
2021-04-24 22:14:30,486 DEBUG asyncio Using proactor: IocpProactor
2021-04-24 22:16:47,934 INFO django.utils.autoreload E:\Python\Yandex\Projects\SocialNetworkOnPythonDjango\SocialNetwork\socketio_app\views.py changed, reloading.
2021-04-24 22:16:47,934 DEBUG asyncio Using proactor: IocpProactor
2021-04-24 22:16:51,816 DEBUG asyncio Using proactor: IocpProactor
2021-04-24 22:20:24,672 INFO django.utils.autoreload E:\Python\Yandex\Projects\SocialNetworkOnPythonDjango\SocialNetwork\socketio_app\views.py changed, reloading.
2021-04-24 22:20:24,672 DEBUG asyncio Using proactor: IocpProactor
2021-04-24 22:20:26,063 WARNING root Invalid token type. Token must be a <class 'bytes'>
2021-04-24 22:20:26,084 WARNING root Invalid token type. Token must be a <class 'bytes'>
2021-04-24 22:20:26,087 WARNING root Invalid token type. Token must be a <class 'bytes'>
2021-04-24 22:20:26,095 WARNING root Invalid token type. Token must be a <class 'bytes'>
2021-04-24 22:20:26,098 WARNING root Invalid token type. Token must be a <class 'bytes'>
2021-04-24 22:20:35,777 INFO django.utils.autoreload E:\Python\Yandex\Projects\SocialNetworkOnPythonDjango\SocialNetwork\socketio_app\views.py changed, reloading.
2021-04-24 22:20:35,777 DEBUG asyncio Using proactor: IocpProactor
2021-04-24 22:20:37,058 WARNING root Invalid token type. Token must be a <class 'bytes'>
2021-04-24 22:20:37,074 WARNING root Invalid token type. Token must be a <class 'bytes'>
2021-04-24 22:20:38,044 WARNING root Invalid token type. Token must be a <class 'bytes'>
2021-04-24 22:20:38,046 WARNING root Invalid token type. Token must be a <class 'bytes'>
2021-04-24 22:20:38,050 WARNING root Invalid token type. Token must be a <class 'bytes'>
2021-04-24 22:20:44,728 INFO django.utils.autoreload E:\Python\Yandex\Projects\SocialNetworkOnPythonDjango\SocialNetwork\socketio_app\views.py changed, reloading.
2021-04-24 22:20:44,729 DEBUG asyncio Using proactor: IocpProactor
2021-04-24 22:20:46,056 WARNING root Invalid token type. Token must be a <class 'bytes'>
2021-04-24 22:20:47,045 WARNING root Invalid token type. Token must be a <class 'bytes'>
2021-04-24 22:20:47,048 WARNING root Invalid token type. Token must be a <class 'bytes'>
2021-04-24 22:20:47,052 WARNING root Invalid token type. Token must be a <class 'bytes'>
2021-04-24 22:20:47,053 WARNING root Invalid token type. Token must be a <class 'bytes'>
2021-04-24 22:24:03,316 WARNING root Invalid token type. Token must be a <class 'bytes'>
2021-04-24 22:24:16,782 INFO django.utils.autoreload E:\Python\Yandex\Projects\SocialNetworkOnPythonDjango\SocialNetwork\socketio_app\views.py changed, reloading.
2021-04-24 22:24:16,782 DEBUG asyncio Using proactor: IocpProactor
2021-04-24 22:24:17,744 WARNING root Invalid token type. Token must be a <class 'bytes'>
2021-04-24 22:24:18,062 WARNING root Invalid token type. Token must be a <class 'bytes'>
2021-04-24 22:24:18,070 WARNING root Invalid token type. Token must be a <class 'bytes'>
2021-04-24 22:24:18,079 WARNING root Invalid token type. Token must be a <class 'bytes'>
2021-04-24 22:24:18,090 WARNING root Invalid token type. Token must be a <class 'bytes'>
2021-04-24 22:24:18,092 WARNING root Invalid token type. Token must be a <class 'bytes'>
2021-04-24 22:24:25,714 WARNING root Invalid token type. Token must be a <class 'bytes'>
2021-04-24 22:24:27,871 INFO django.utils.autoreload E:\Python\Yandex\Projects\SocialNetworkOnPythonDjango\SocialNetwork\socketio_app\views.py changed, reloading.
2021-04-24 22:24:27,871 DEBUG asyncio Using proactor: IocpProactor
2021-04-24 22:24:28,833 WARNING root Invalid token type. Token must be a <class 'bytes'>
2021-04-24 22:24:28,835 WARNING root Invalid token type. Token must be a <class 'bytes'>
2021-04-24 22:24:29,056 WARNING root Invalid token type. Token must be a <class 'bytes'>
2021-04-24 22:24:29,072 WARNING root Invalid token type. Token must be a <class 'bytes'>
2021-04-24 22:24:29,078 WARNING root Invalid token type. Token must be a <class 'bytes'>
2021-04-24 22:24:29,081 WARNING root Invalid token type. Token must be a <class 'bytes'>
2021-04-24 22:24:30,047 WARNING root Invalid token type. Token must be a <class 'bytes'>
2021-04-24 22:24:48,080 INFO django.utils.autoreload E:\Python\Yandex\Projects\SocialNetworkOnPythonDjango\SocialNetwork\socketio_app\views.py changed, reloading.
2021-04-24 22:24:48,080 DEBUG asyncio Using proactor: IocpProactor
2021-04-24 22:24:49,043 WARNING root Invalid token type. Token must be a <class 'bytes'>
2021-04-24 22:24:49,233 WARNING root Invalid token type. Token must be a <class 'bytes'>
2021-04-24 22:24:49,248 WARNING root Invalid token type. Token must be a <class 'bytes'>
2021-04-24 22:24:50,059 WARNING root Invalid token type. Token must be a <class 'bytes'>
2021-04-24 22:24:50,080 WARNING root Invalid token type. Token must be a <class 'bytes'>
2021-04-24 22:24:50,094 WARNING root Invalid token type. Token must be a <class 'bytes'>
2021-04-24 22:24:50,102 WARNING root Invalid token type. Token must be a <class 'bytes'>
2021-04-24 22:25:03,824 WARNING root Invalid token type. Token must be a <class 'bytes'>
2021-04-24 22:26:32,278 INFO django.utils.autoreload E:\Python\Yandex\Projects\SocialNetworkOnPythonDjango\SocialNetwork\socketio_app\views.py changed, reloading.
2021-04-24 22:26:32,280 DEBUG asyncio Using proactor: IocpProactor
2021-04-24 22:26:33,997 WARNING root Invalid token type. Token must be a <class 'bytes'>
2021-04-24 22:26:34,060 WARNING root Invalid token type. Token must be a <class 'bytes'>
2021-04-24 22:26:34,081 WARNING root Invalid token type. Token must be a <class 'bytes'>
2021-04-24 22:26:34,083 WARNING root Invalid token type. Token must be a <class 'bytes'>
2021-04-24 22:26:34,085 WARNING root Invalid token type. Token must be a <class 'bytes'>
2021-04-24 22:26:34,089 WARNING root Invalid token type. Token must be a <class 'bytes'>
2021-04-24 22:27:20,118 INFO django.utils.autoreload E:\Python\Yandex\Projects\SocialNetworkOnPythonDjango\SocialNetwork\socketio_app\views.py changed, reloading.
2021-04-24 22:27:20,119 DEBUG asyncio Using proactor: IocpProactor
2021-04-24 22:27:21,045 WARNING root Invalid token type. Token must be a <class 'bytes'>
2021-04-24 22:27:21,047 WARNING root Invalid token type. Token must be a <class 'bytes'>
2021-04-24 22:27:21,260 WARNING root Invalid token type. Token must be a <class 'bytes'>
2021-04-24 22:27:22,058 WARNING root Invalid token type. Token must be a <class 'bytes'>
2021-04-24 22:27:22,065 WARNING root Invalid token type. Token must be a <class 'bytes'>
2021-04-24 22:27:22,079 WARNING root Invalid token type. Token must be a <class 'bytes'>
2021-04-24 22:28:34,015 INFO django.utils.autoreload E:\Python\Yandex\Projects\SocialNetworkOnPythonDjango\SocialNetwork\socketio_app\views.py changed, reloading.
2021-04-24 22:28:34,016 DEBUG asyncio Using proactor: IocpProactor
2021-04-24 22:28:35,043 WARNING root Invalid token type. Token must be a <class 'bytes'>
2021-04-24 22:28:35,046 WARNING root Invalid token type. Token must be a <class 'bytes'>
2021-04-24 22:28:35,992 WARNING root Invalid token type. Token must be a <class 'bytes'>
2021-04-24 22:28:36,055 WARNING root Invalid token type. Token must be a <class 'bytes'>
2021-04-24 22:28:36,070 WARNING root Invalid token type. Token must be a <class 'bytes'>
2021-04-24 22:28:36,071 WARNING root Invalid token type. Token must be a <class 'bytes'>
2021-04-24 22:28:38,602 INFO django.utils.autoreload E:\Python\Yandex\Projects\SocialNetworkOnPythonDjango\SocialNetwork\socketio_app\views.py changed, reloading.
2021-04-24 22:28:38,602 DEBUG asyncio Using proactor: IocpProactor
2021-04-24 22:28:40,005 WARNING root Invalid token type. Token must be a <class 'bytes'>
2021-04-24 22:28:40,060 WARNING root Invalid token type. Token must be a <class 'bytes'>
2021-04-24 22:28:40,075 WARNING root Invalid token type. Token must be a <class 'bytes'>
2021-04-24 22:28:40,080 WARNING root Invalid token type. Token must be a <class 'bytes'>
2021-04-24 22:28:40,083 WARNING root Invalid token type. Token must be a <class 'bytes'>
2021-04-24 22:28:41,051 WARNING root Invalid token type. Token must be a <class 'bytes'>
2021-04-24 22:28:58,825 INFO django.utils.autoreload E:\Python\Yandex\Projects\SocialNetworkOnPythonDjango\SocialNetwork\socketio_app\views.py changed, reloading.
2021-04-24 22:28:58,826 DEBUG asyncio Using proactor: IocpProactor
2021-04-24 22:28:59,993 WARNING root Invalid token type. Token must be a <class 'bytes'>
2021-04-24 22:29:37,565 INFO django.utils.autoreload E:\Python\Yandex\Projects\SocialNetworkOnPythonDjango\SocialNetwork\socketio_app\views.py changed, reloading.
2021-04-24 22:29:37,565 DEBUG asyncio Using proactor: IocpProactor
2021-04-24 22:29:39,998 WARNING root Invalid token type. Token must be a <class 'bytes'>
2021-04-24 22:30:33,024 WARNING root Invalid token type. Token must be a <class 'bytes'>
2021-04-24 22:34:30,556 INFO django.utils.autoreload E:\Python\Yandex\Projects\SocialNetworkOnPythonDjango\SocialNetwork\socketio_app\views.py changed, reloading.
2021-04-24 22:34:30,557 DEBUG asyncio Using proactor: IocpProactor
2021-04-24 22:39:17,900 INFO django.utils.autoreload E:\Python\Yandex\Projects\SocialNetworkOnPythonDjango\SocialNetwork\socketio_app\views.py changed, reloading.
2021-04-24 22:39:17,901 DEBUG asyncio Using proactor: IocpProactor
2021-04-24 22:39:22,085 INFO django.utils.autoreload E:\Python\Yandex\Projects\SocialNetworkOnPythonDjango\SocialNetwork\socketio_app\views.py changed, reloading.
2021-04-24 22:39:22,085 DEBUG asyncio Using proactor: IocpProactor
2021-04-24 22:41:38,415 INFO django.utils.autoreload E:\Python\Yandex\Projects\SocialNetworkOnPythonDjango\SocialNetwork\socketio_app\views.py changed, reloading.
2021-04-24 22:41:38,416 DEBUG asyncio Using proactor: IocpProactor
2021-04-24 22:48:59,950 INFO django.utils.autoreload E:\Python\Yandex\Projects\SocialNetworkOnPythonDjango\SocialNetwork\socketio_app\views.py changed, reloading.
2021-04-24 22:48:59,950 DEBUG asyncio Using proactor: IocpProactor
2021-04-24 22:55:14,615 INFO django.utils.autoreload E:\Python\Yandex\Projects\SocialNetworkOnPythonDjango\SocialNetwork\socketio_app\views.py changed, reloading.
2021-04-24 22:55:14,616 DEBUG asyncio Using proactor: IocpProactor
